### PR TITLE
added custom display layout

### PR DESCRIPTION
**Pull request by adilahmeddev**
The changes to GP-2040 are on this fork https://github.com/adilahmeddev/GP2040-CE-ERGOSHIFT-DISPLAY

still wip and doesn't look great but its working

P.S: Thanks for your work on this, just finished building my ergoshift and its great

### CODE REVIEW

**Comment by adilahmeddev** [comment]
I think I've missed the correct default pin mapping. Will fix after work.

**Comment by mizma** [comment]
Wow! that looks awesome!  I don't really have time to look until weekend.  let me check it out later and consider how to merge this.

**Comment by mizma** [comment]
Thanks for the contribution.  There are some things I would like to discuss

Adding the new layout definition for #define BUTTON_LAYOUT in BoardConfig.h without pointing to the correct source code would confuse other people who wants to build the firmware (their build will fail if they add the changes in this repo to the original upstream codebase). 

should we just add your binary and link to your repo in the readme inside the firmware directory?

P.S. Sorry for the complication due to me not having the firmware upstreamed yet...

**Comment by adilahmeddev** [comment]
No worries! 
I'm not sure what the process is for getting a board added to the upstream, but I could try and open a pull request and see where it goes. 

In the mean time your idea makes sense.

You could also fork the repo and we can add the changes there.  Might make it easier for others if all the code bases are under the same account.

**Comment by adilahmeddev** [comment]
Just read through your PR on their repo, I might try submitting the display configuration on its own for now

**Comment by mizma** [comment]
OK, could you revert the BoardConfig.h to original and I will merge this PR.
I will add the link to your repo for the layout.

I'll try re-opening the PR for adding the board upstream.

**Comment by adilahmeddev** [comment]
I've reverted the BoardConfig.h changes

**Pull request merged**
